### ISSUE TITLE
Behaviour of `put` in presence of references/pointers

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#10]
@sequenze @michele-loreti We have discussed in the past whether

```
SomeClass object;
mySpace.put(object);
```

places (1) a deep copy of `object` or (2) reference. 

The main difference is that

```
object.update()
```

has no effect in the tuple space in (1) but it does in (2).

In my view:
(1) seems in line with the tuple space paradigm;
(2) seems in line with standard OO containers classes;

I would tend to prefer (1) since (2) does not make much sense when one goes distributed. In particular, putting a reference in a remote space does not make much sense (the reference is useless in the remote place) so one would necessarily go for (1). And one should then support (1) locally for the sake of uniformity. But I can also see the advantages in (2) for local tuple spaces.

Btw. which choice did you do in jSpaces and dotSpaces?

@MarcStorm I guess you had a similar issue in goSpace. Golang is pass-by-value, but as in C-like languages passing the value of an array/slice is just the pointer to the first element. As far as I remember we agreed on "ignoring" pointer-based data types. Can you please confirm?

**Comment by sequenze** [comment]
In dotSpace, put  always places a reference. However, the get/query operations performs a deep copy of the object.

I chose to copy the object, because that gives coherency to the framework. I mean, it would make it harder to use the framework, if a local space allowed different features from the networked space.

Conversely, it is easy to develop an application locally and once everything works, then replace the FifoSpace with RemoteSpace.

+1 for deep copy on **get** and **query**.

**Comment by albertolluch** [comment]
@sequenze : if `put` places a reference, then

```
SomeClass object;
mySpace.put(object);
object.update();
ITuple tuple = mySpace.get(typeof(object);
```

has different behaviour depending on whether `mySpace` is local or remote. If it is local, you get a deep copy of the object after the update, while if it is remote you get a copy of the object before the update. Is this the way dotSpace works? Do you think that this difference of behaviour should be avoided?

We could also accept that behavour, but we should definitively describe it in the API (the one that I am trying to update these days, plus the one of the individual language).

**Comment by sequenze** [comment]
> has different behaviour depending on whether mySpace is local or remote. If it is local, you get a deep copy of the object after the update, while if it is remote you get a copy of the object before the update. Is this the way dotSpace works? Do you think that this difference of behaviour should be avoided?

We could also accept that behavour, but we should definitively describe it in the API (the one that I am trying to update these days, plus the one of the individual language).

**Well I remembered wrong. I actually considered this when i developed dotSpace**
The following is how dotSpace approaches this:
Put: places a deep copy.
Query: returns a deep copy.

Both of them are equally important, otherwise you can change the values in the tuple using a reference.

if query didnt copy the tuple one could hack the values locally.

Fx: this would be possible with query:

**For process1:**
Tuple t = new Tuple("Hello");
Ts.put(t);
Tuple t2 = Ts.query("hello");
ts.Get("P2");
t2[0] = "bye!";
ts.Put("P1);

**For process2:**
Tuple t2 = Ts.query("hello");
ts.Put("P2");
ts.Get("P1);
print(t2); // "bye!" would be printed.

_EDIT: get doesn't perform a deep copy._

**Comment by albertolluch** [comment]
So dotSpace behaves as I propose. No change needed then, right?

**Comment by sequenze** [comment]
Yup. As far as i know :)

**Comment by albertolluch** [comment]
I have discussed this with @michele-loreti. We all agree that spaces must contain *deep copies* of data items. Closing this issue.
