### ISSUE TITLE
Decide if RemoteSpace could be removed and use instead just one constructor NewSpace

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#3]
Whether the space is remote or not can be inferred from the URI.

**Comment by albertolluch** [comment]
@luhac: this suggestion is strongly related to the ongoing discussion on interfaces and implementation of spaces (#5). Let's fix that before.

**Comment by sequenze** [comment]
Are you guys talking about a factory pattern or?

**Comment by ghost** [comment]
@sequenze 
When creating a new space with a contructor /allocation function, the URI contains all the information regarding the location of the space. The question is if it makes sense to provide it in another constructor/allocation function, e.g. `RemoteSpace` as mentioned in the specification, when it can happen when creating the space.

In my opinion, since one is creating a space, one should not discriminate between local and remote spaces. One should just be able to "connect" to the space resource, without having to worry whether it is local or remote.

**Comment by albertolluch** [comment]
After all this is language dependent. The point is whether to suggest it as a convention or not. At this stage of the work we can be liberal in the conventions and see how different variants work. 

So, @luhac, feel free to implement in goSpaces but we shall leave Java and C# as they are.

Closing this...
