### ISSUE TITLE
Examples in separate repositories?

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#6]

**Comment by albertolluch** [comment]
@luhac proposes that examples should be available in separate repositories. So, for instance, for go one would have something like:
- https://github.com/pSpaces/goSpace
- https://github.com/pSpaces/goSpace-examples
The rationale is that one does not need examples for fresh projects. @sequenze @michele-loreti what do you think?

**Comment by sequenze** [comment]
I completely agree. I thought of this as well during the development of dotSpaces but I decided not to raise an issue with this as it would be more convenient for the students to get it all in one project. However, in terms of clarity and coherency of projects they **should** be separated.

+1 from me :)

**Comment by albertolluch** [comment]
Yes, this is what @luhac and me discussed. Please feel free to implement the separation on dotSpace.

**Comment by sequenze** [comment]
Okay, I will do this as soon as I get the time :)

**Comment by michele-loreti** [comment]
I agree. It is more convenient to have different repositories for core-libraries and examples. This also because we could develop applications that, developed using the different languages, will be distributed in different repositories. 

Since all of us agree on this point, I mark this issue as closed.
